/**:
  ros__parameters:
    gyro_bias_threshold: 0.003 # [rad/s]
    timer_callback_interval_sec: 0.5 # [sec]
    diagnostics_updater_interval_sec: 0.5 # [sec]
    # straight_motion_ang_vel_upper_limit: 0.015 # [rad/s]
    vehicle_stop_velocity_threshold: 0.1 # [m/s] 停車判定の速度閾値
    vehicle_stop_angular_velocity_threshold: 0.01 # [rad/s] 停車判定の角速度閾値
